spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost

messaging:
  exchange: payment-system
  contract:
    queue: contract-service
    routing-key: contract-event

server:
  port: 0
