spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lolxaxlol
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    listener:
      simple:
        concurrency: 5

messaging:
  exchange: payment-system
  contract:
    queue: contract-service
    routing-key: contract-event
