spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: guest
    password: guest
    host: rabbit
    listener:
      simple:
        concurrency: 5
        default-requeue-rejected: false

messaging:
  exchange: payment-system
  contract:
    queue: contract-service
    routing-key: contract-event
