spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: guest
    password: guest
    host: rabbit
    listener:
      simple:
        concurrency: 5
        default-requeue-rejected: false

messaging:
  exchange: entry-exchange
  contract-create:
    queue: contract-service
  fast-contract:
    queue: minutes-contract-queue
    routing-key: minutes
  normal-contract:
    queue: day-contract-queue
    routing-key: day
  slow-contract:
    queue: month-contract-queue
    routing-key: month
  payment-withdraw:
    queue: payment-withdraw-queue
